apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"details","service":"details"},"name":"details","namespace":"default"},"spec":{"ports":[{"name":"http","port":9080}],"selector":{"app":"details"}}}
    creationTimestamp: "2024-12-05T06:48:35Z"
    labels:
      app: details
      service: details
    name: details
    namespace: default
    resourceVersion: "80650"
    uid: c8f2879a-32e7-4fd9-a651-4e36d364b3b8
  spec:
    clusterIP: 10.110.24.236
    clusterIPs:
    - 10.110.24.236
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 9080
      protocol: TCP
      targetPort: 9080
    selector:
      app: details
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"productpage","service":"productpage"},"name":"productpage","namespace":"default"},"spec":{"ports":[{"name":"http","port":9080}],"selector":{"app":"productpage"}}}
    creationTimestamp: "2024-12-05T06:48:35Z"
    labels:
      app: productpage
      service: productpage
    name: productpage
    namespace: default
    resourceVersion: "80729"
    uid: 0eb8f00a-ea07-42fe-b0d8-72577fefbbc1
  spec:
    clusterIP: 10.99.214.49
    clusterIPs:
    - 10.99.214.49
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 9080
      protocol: TCP
      targetPort: 9080
    selector:
      app: productpage
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"ratings","service":"ratings"},"name":"ratings","namespace":"default"},"spec":{"ports":[{"name":"http","port":9080}],"selector":{"app":"ratings"}}}
    creationTimestamp: "2024-12-05T06:48:35Z"
    labels:
      app: ratings
      service: ratings
    name: ratings
    namespace: default
    resourceVersion: "80659"
    uid: a0a39a38-a6a0-4a25-a6eb-289041e9f0aa
  spec:
    clusterIP: 10.107.200.90
    clusterIPs:
    - 10.107.200.90
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 9080
      protocol: TCP
      targetPort: 9080
    selector:
      app: ratings
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"reviews","service":"reviews"},"name":"reviews","namespace":"default"},"spec":{"ports":[{"name":"http","port":9080}],"selector":{"app":"reviews"}}}
    creationTimestamp: "2024-12-05T06:48:35Z"
    labels:
      app: reviews
      service: reviews
    name: reviews
    namespace: default
    resourceVersion: "80673"
    uid: f6443091-df07-4128-8298-6b6d530a9e7d
  spec:
    clusterIP: 10.98.130.95
    clusterIPs:
    - 10.98.130.95
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      port: 9080
      protocol: TCP
      targetPort: 9080
    selector:
      app: reviews
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
