apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: '{"apiVersion":"networking.istio.io/v1alpha3","kind":"VirtualService","metadata":{"annotations":{},"name":"frontend-ingress","namespace":"online-boutique"},"spec":{"gateways":["frontend-gateway"],"hosts":["*"],"http":[{"route":[{"destination":{"host":"frontend.online-boutique.svc.cluster.local","port":{"number":80},"subset":"original"},"weight":70},{"destination":{"host":"frontend.online-boutique.svc.cluster.local","port":{"number":80},"subset":"v1"},"weight":30}]}]}}

      '
  creationTimestamp: '2025-02-12T07:39:29Z'
  generation: 34
  managedFields:
  - apiVersion: networking.istio.io/v1alpha3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: '2025-03-20T09:56:04Z'
  - apiVersion: networking.istio.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:gateways: {}
        f:hosts: {}
        f:http: {}
    manager: kiali
    operation: Update
    time: '2025-04-03T12:42:48Z'
  name: frontend-ingress
  namespace: online-boutique
  resourceVersion: '1532774'
  uid: 0d76f9c0-f5ba-470b-b9dd-9fd6639b7940
spec:
  gateways:
  - frontend-gateway
  hosts:
  - '*'
  http:
  - route:
    - destination:
        host: frontend.online-boutique.svc.cluster.local
        subset: original
      weight: 55
    - destination:
        host: frontend.online-boutique.svc.cluster.local
        subset: v1
      weight: 45
